#include <stdio.h>
#include <stdint.h>
#include <bcc/bcc.h>  // For secondary core booting
#include "injector.h"

#define __USING_IDE__
#define __DEBUG__

    //////////////////////////
   // SafeTI configuration //
  //////////////////////////

// Set a target address for SafeTI accesses to initiate from
#ifndef __TARGET_ADDR__
  #define __TARGET_ADDR__ 0x0A000000
#endif

// Scripted descriptor type, size and sweep option from Makefile
// Type of access ->  1=READ, 2=WRITE
#ifndef  __INJ_TYPE__
  #define __INJ_TYPE__ INJ_OP_READ
#endif
// Access size in bytes
#ifndef __INJ_SIZE__
  #define __INJ_SIZE__ 1024
#endif
// Delay in number of clock cycles
#ifndef __INJ_DELAY__
  #define __INJ_DELAY__ 20
#endif
// Set SafeTI traffic injection in loop mode
#ifndef __INJ_LOOP__
  #define __INJ_LOOP__ 0
#endif
// Select SafeTI module from the implemented in HW (review injector.h and HW)
#ifndef __INJ_SELECTOR__
  #define __INJ_SELECTOR__ SAFETI_AXI_0
#endif


// If needed if you do not want to the IDE grais-out the code
#ifndef __CORE__
  #define __CORE__
#endif

// Compile variable for distinction between simulation and FPGA execution
#ifndef __FPGA__
  #define __FPGA__ 0
#endif

#ifndef NCPU                // Set number of cores to use during experiment
  #define NCPU (1U)         // 4 or 6 (depending on the bitstream configuration)
#endif

// Dumbo sleep function
void sleep(unsigned int sleep_cnt) {
  __asm__ __volatile__ (
    ".sleep_loop%=:   \n\t"
    "addi %0, %0, -1   \n\t"
    "bne  %0, zero, .sleep_loop%= \n\t"
    ://   %0
    : "r"(sleep_cnt)
  );
}

// Secondary CPU cores programs
void secondary_cores_function() {
  int core;
  __asm__ __volatile__("csrr %0, 0xf14"  : "=r"(core));
  switch(core) {
    case 0:
      break;
    default:
      while(1);
} }


#if(__FPGA__ != 0)
// Secondary CPU cores enable function
void bootSecondaryCores(int ncpu) {
  uint64_t stack[ncpu-1][4096 / 8];
  for(int i = 1; i < ncpu; i++) {
    __bcc_startinfo[i].pc = &secondary_cores_function;
    __bcc_startinfo[i].sp = (uintptr_t)&stack[i-1][0];
    bcc_start_processor(i);
} }
#endif //__FPGA__ != 0


// Template for SafeTI traffic descriptor program
void inj_program_custom(unsigned int SEL, unsigned int DELAY_SIZE, unsigned int DESC_TYPE, unsigned int SIZE, unsigned int ATTACK_ADDR) {
  unsigned int i;
  inj_reset(SEL);
  inj_reset_counters(SEL);

  // 524288 is max size for a single transaction/delay descriptor,
  // thus, use multiple descriptors if needed. First program DELAY descriptors.
  for(i = 0; DELAY_SIZE > 524288; i++) {
    // (SEL, DESC_TYPE, SIZE, DESC_ATTACK_ADDR, COUNT, LAST, INTERRUPTION_EN)
    program_descriptor(SEL, INJ_OP_DELAY, 524288, 0, 0, 0, 0);
    DELAY_SIZE = DELAY_SIZE - 524288;
  }
  program_descriptor(SEL, INJ_OP_DELAY, DELAY_SIZE, 0, 0, 0, 0);

  // Then, program which traffic type is set by DESC_TYPE
  for(i = 0; SIZE > 524288; i++) {
    // Here put the descriptor you want to be programmed
    // (SEL, DESC_TYPE, SIZE, DESC_ATTACK_ADDR, COUNT, LAST, INTERRUPTION_EN)
    program_descriptor(SEL, DESC_TYPE, 524288, ATTACK_ADDR+0x80000*i, 0, 0, 0);
    SIZE = SIZE - 524288;
  }
  program_descriptor(SEL, DESC_TYPE, SIZE, ATTACK_ADDR+0x80000*i, 0, 1, 0);

  // At last, start traffic injector
  // (SEL, ENABLE, QUEUE_EN, INT_PROG_COMPL, INT_ERROR, INT_NET_ERROR, FREEZE_INT)
  program_configuration(SEL, 1, __INJ_LOOP__, 1, 0, 0, 0);
}

int main(void) {
  // Initialize secondary CPUs
#if(__FPGA__ != 0)
  bootSecondaryCores(NCPU);
#else
  secondary_cores_function();
#endif //__FPGA__ != 0
  sleep(50); // Let Secondary cores catch up


  // CPU0 main program
  printf("\nSTART EXPERIMENTS\n\n");
  unsigned int inj_size, inj_req_cnt, inj_prog_compl_cnt;

  inj_size  = __INJ_SIZE__;

  // Reset SafeTI counters
  inj_reset_counters(__INJ_SELECTOR__);

  // Write the descriptor program and start traffic injection
  if(inj_size != 0)
    inj_program_custom(__INJ_SELECTOR__, __INJ_DELAY__, __INJ_TYPE__, inj_size, __TARGET_ADDR__);

  // Let SafeTI do some rounds
  sleep(5000);

  // Disable injector while letting to finish any ongoing transaction
  if(inj_size != 0) {
    inj_reset(__INJ_SELECTOR__);
    while(inj_check_run(__INJ_SELECTOR__) != 0) {
      printf("Waiting for injector to stop.\n");
    }
  }

  // SafeTI interruptions are generated by set flags during program_configuration().
  // The set flag INT_PROG_COMPL allows to count the number of times SafeTI completed
  // its programming, which should be no greater than 1 if __INJ_LOOP__ = 0.
  // The number of SafeTI counter interruptions may vary depending on the configuration.
  inj_req_cnt = inj_read_counter(__INJ_SELECTOR__, INJ_CNT_ACCESS);
  inj_prog_compl_cnt = inj_read_counter(__INJ_SELECTOR__, INJ_CNT_INT);

  printf("Number of SafeTI accesses: %u\n", inj_req_cnt);
  printf("Number of SafeTI interruptions: %u\n", inj_prog_compl_cnt);

  printf("\nFINISHED EXPERIMENT\n\n");


  return 0;
}
